#!/bin/bash
#数据库IP
dbserver='x.x.x.x'
#数据库用户名
dbuser='xxx'
#数据库密码
dbpasswd='xxxxx'
#备份数据库,多个库用空格隔开
dbname='xxx'
#备份时间
backtime=`date +%Y%m%d%H%M`
out_time=`date +%Y%m%d%H%M%S`
#备份输出路径
backpath='/data/backup/mysql/'
logpath='/data/backup/logs/'

echo "################## ${backtime} #############################" 
echo "开始备份" 
#日志记录头部
echo "" >> ${logpath}/${dbname}_backup.log
echo "-------------------------------------------------" >> ${logpath}/${dbname}_backup.log
echo "备份开始时间为${backtime},备份数据库 ${dbname} 开始" >> ${logpath}/${dbname}_backup.log

#正式备份数据库
for DB in $dbname; do
  source=`/usr/local/mysql5.7.21/bin/mysqldump  -h ${dbserver} -u ${dbuser} -p${dbpasswd} ${DB} > ${backpath}/${DB}-${out_time}.sql` 2>> ${logpath}/${dbname}_backup.log;
  #备份成功以下操作
  if [ "$?" == 0 ];then
    cd $backpath
    #为节约硬盘空间，将数据库压缩
    tar jcf ${DB}-${out_time}.tar.gz ${DB}-${out_time}.sql > /dev/null
    #删除原始文件，只留压缩后文件
    rm -f ${DB}-${out_time}.sql
    #删除15天前备份，也就是只保存15天内的备份
    find $backpath -name "*.tar.gz" -type f -mtime +15 -exec rm -rf {} \; > /dev/null 2>&1
    echo "数据库 ${dbname} 备份成功!!" >> ${logpath}/${dbname}_backup.log
  else
  #备份失败则进行以下操作
  echo "数据库 ${dbname} 备份失败!!" >> ${logpath}/${dbname}_backup.log
  fi
done

echo "完成备份"
echo "################## ${backtime} #############################"
